name: 🐛 Defect Report
description: Report a defect or bug in existing functionality
title: "DEF-XXXXX: [Brief description of the defect]"
labels: ["defect", "needs-triage"]
projects: ["gonogo/1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Defect Report

        Thanks for reporting a defect! This streamlined template captures the essential information needed for investigation.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the issue
      placeholder: |
        1. Navigate to blog homepage
        2. Enter "python" in search box
        3. Click search button
        4. Observe results
    validations:
      required: false

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "Search should return blog posts containing the keyword"
    validations:
      required: false

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Search returns 'No results found' message"
    validations:
      required: false

  - type: textarea
    id: business-impact
    attributes:
      label: Business Impact
      description: How does this affect users and business?
      placeholder: "Users cannot find content, reduced engagement"
    validations:
      required: false

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages & Logs (Optional)
      description: Console errors, logs, or error messages
      placeholder: |
        ```
        [Paste any error messages or console output]
        ```
    validations:
      required: false

  - type: textarea
    id: defect-analysis
    attributes:
      label: Debug and Root Cause Analysis
      description: During or after resolution, document why the defect occured
      placeholder: |
        ```
        [Write the detailed analysis]
        ```
    validations:
      required: false

  - type: input
    id: workaround
    attributes:
      label: Workaround Available
      description: Is there a temporary workaround?
      placeholder: "Yes - users can browse by category | No workaround available"
    validations:
      required: false

  - type: checkboxes
    id: gdpr-impact
    attributes:
      label: GDPR Considerations
      description: Does this defect have privacy implications?
      options:
        - label: Personal data may be affected
        - label: Consent system affected
        - label: Data retention impacted
        - label: Not applicable