name: 📋 Epic
description: Create a new epic for organizing related user stories
title: "EP-XXXXX: [Brief description of the epic]"
labels: ["epic", "needs-triage"]
projects: ["gonogo/1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Epic Creation

        Create an epic to organize related user stories.

        ⚠️ **Important**: The "Epic Description" field below is automatically displayed in the Requirements Traceability Matrix (RTM) reports. Keep it concise and clear for optimal RTM presentation.

  - type: textarea
    id: epic-description
    attributes:
      label: Epic Description
      description: |
        🎯 **RTM Integration**: This description appears directly in Requirements Traceability Matrix reports.

        Write a clear, concise description in user story format:
        - Use "As a [user], I want [goal], So that [benefit]" format
        - Add 1-2 sentences explaining the epic's purpose
        - **Limit: 500 characters** (hard limit imposed by RTM import system)
        - Avoid excessive markdown formatting (it will be cleaned for RTM display)
        - Focus on the essential user story and business purpose
      placeholder: |
        **As a** blog visitor
        **I want** advanced search capabilities
        **So that** I can quickly find relevant content

        Comprehensive search functionality for content discovery.
    validations:
      required: true

  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: |
        📝 **Extensive Details**: Use this field for comprehensive epic documentation.

        This field is NOT displayed in RTM reports - use it for:
        - Detailed requirements and specifications
        - Technical implementation notes
        - Stakeholder context and background
        - Links to external resources
        - Any extensive information that doesn't fit in the 500-character RTM description
      placeholder: |
        ## Background
        Provide detailed context about why this epic is needed...

        ## Technical Considerations
        - Architecture implications
        - Integration requirements
        - Performance considerations

        ## Stakeholder Impact
        - User experience improvements
        - Business process changes
        - Training requirements

        ## External Resources
        - [Design mockups](https://example.com)
        - [Requirements document](https://example.com)
        - [Technical specifications](https://example.com)
    validations:
      required: false

  - type: textarea
    id: business-value
    attributes:
      label: Business Value
      description: Why is this important?
      placeholder: "Improves user experience and content discovery"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Epic priority level
      options:
        - low
        - medium
        - high
        - critical
      default: 1
    validations:
      required: false

  - type: input
    id: total-story-points
    attributes:
      label: Total Story Points (Optional)
      description: Total estimated story points for this epic
      placeholder: "50"
    validations:
      required: false

  - type: input
    id: completed-story-points
    attributes:
      label: Completed Story Points (Optional)
      description: Story points completed so far
      placeholder: "20"
    validations:
      required: false

  - type: input
    id: target-release-version
    attributes:
      label: Target Release Version (Optional)
      description: Target release for this epic
      placeholder: "v1.2.0"
    validations:
      required: false

  - type: checkboxes
    id: component
    attributes:
      label: Components
      description: Components this epic affects (will be automatically populated based on child User Stories)
      options:
        - label: Frontend/UI
        - label: Backend/API
        - label: Database
        - label: Security/GDPR
        - label: Testing
        - label: CI/CD
        - label: Documentation
    validations:
      required: false

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: How will we know it's successful?
      placeholder: |
        - [ ] Users can search blog posts by keyword
        - [ ] Search results load within 2 seconds
    validations:
      required: false

  - type: textarea
    id: user-stories
    attributes:
      label: Planned User Stories
      description: What user stories will be part of this epic?
      placeholder: |
        - US-XXXXX: Basic content search
        - US-XXXXX: Advanced filtering
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What other epics or external requirements does this depend on?
      placeholder: |
        - EP-XXXXX: Other epic that must be completed first
        - External service or infrastructure requirements
    validations:
      required: false

  - type: dropdown
    id: risk-level
    attributes:
      label: Risk Level
      description: Overall risk assessment for this epic
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: false

  - type: textarea
    id: risks-mitigation
    attributes:
      label: Risks and Mitigation
      description: What are the main risks and how will they be mitigated?
      placeholder: |
        - Risk - Performance may impact site speed
        - Mitigation - Implement caching strategy
    validations:
      required: false

  - type: checkboxes
    id: gdpr-considerations
    attributes:
      label: GDPR Considerations
      description: Does this epic involve personal data?
      options:
        - label: Involves personal data processing
        - label: GDPR compliance review needed
        - label: Not applicable

  - type: textarea
    id: gdpr-considerations-details
    attributes:
      label: GDPR Considerations Details (Optional)
      description: Detailed GDPR considerations if applicable
      placeholder: "Describe any privacy implications, data processing needs, or compliance requirements"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        ## 📊 Requirements Traceability Matrix (RTM) Integration

        **Fields displayed in RTM reports:**
        - ✅ **Epic Description** → Main display (500 char limit) - keep concise!
        - ✅ **Component** → System component classification for organization
        - ✅ **Epic Status** → Progress tracking
        - ✅ **GitHub Links** → Direct links to this issue
        - ✅ **User Story Progress** → Calculated automatically

        **Fields NOT displayed in RTM (for detailed documentation):**
        - 📝 **Detailed Description** → Comprehensive epic documentation
        - 📝 **Business Value** → Internal stakeholder reference
        - 📝 **Success Criteria** → Detailed acceptance criteria
        - 📝 **Risks & Dependencies** → Project management details

        **After creating this epic:**
        1. Link related User Stories using "Parent Epic: EP-XXXXX" in their descriptions
        2. Epic progress will be automatically calculated in RTM reports
        3. View RTM reports: `python tools/dynamic_rtm_demo.py --html`

        **Component Inheritance System:**
        - **Epic Components**: Automatically populated based on child User Stories
        - **Unique Components**: Each component appears only once, even if multiple User Stories use it
        - **Dynamic Updates**: Components update automatically as User Stories are added/modified
        - **Manual Override**: Components can be manually selected during epic creation if needed

        **Component Types**:
        - **Frontend/UI**: User interface, web components, styling, templates
        - **Backend/API**: Server logic, API endpoints, business rules, services
        - **Database**: Schema changes, migrations, data models, queries
        - **Security/GDPR**: Authentication, authorization, privacy compliance
        - **Testing**: Test infrastructure, quality assurance tools, test automation
        - **CI/CD**: Build pipelines, deployment automation, GitHub Actions
        - **Documentation**: User guides, technical docs, API documentation

        💡 **Best Practice**: Use Epic Description for RTM (concise), Detailed Description for comprehensive documentation!
