name: 📋 Epic
description: Create a new epic for organizing related user stories
title: "EP-XXXXX: [Brief description of the epic]"
labels: ["epic", "needs-triage"]
projects: ["gonogo/1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Epic Creation

        Create an epic to organize related user stories. Keep it simple - you can add details later.

  - type: textarea
    id: epic-description
    attributes:
      label: Epic Description
      description: What do we want to achieve and why?
      placeholder: |
        **As a** blog visitor
        **I want** advanced search capabilities
        **So that** I can quickly find relevant content
    validations:
      required: true

  - type: textarea
    id: business-value
    attributes:
      label: Business Value
      description: Why is this important?
      placeholder: "Improves user experience and content discovery"
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: Success Criteria
      description: How will we know it's successful?
      placeholder: |
        - [ ] Users can search blog posts by keyword
        - [ ] Search results load within 2 seconds
    validations:
      required: false

  - type: textarea
    id: user-stories
    attributes:
      label: Planned User Stories
      description: What user stories will be part of this epic?
      placeholder: |
        - US-XXXXX: Basic content search
        - US-XXXXX: Advanced filtering
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What other epics or external requirements does this depend on?
      placeholder: |
        - EP-XXXXX: Other epic that must be completed first
        - External service or infrastructure requirements
    validations:
      required: false

  - type: dropdown
    id: risk-level
    attributes:
      label: Risk Level
      description: Overall risk assessment for this epic
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: false

  - type: textarea
    id: risks-mitigation
    attributes:
      label: Risks and Mitigation
      description: What are the main risks and how will they be mitigated?
      placeholder: |
        - Risk - Performance may impact site speed
        - Mitigation - Implement caching strategy
    validations:
      required: false

  - type: checkboxes
    id: gdpr-considerations
    attributes:
      label: GDPR Considerations
      description: Does this epic involve personal data?
      options:
        - label: Involves personal data processing
        - label: GDPR compliance review needed
        - label: Not applicable