name: 📖 User Story
description: Create a new user story within an epic
title: "US-XXXXX: [Brief description of the user story]"
labels: ["user-story", "needs-triage"]
projects: ["gonogo/1"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## User Story Creation

        Create a user story within an epic. Keep it simple - you can add details later.

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: What do you want to achieve?
      placeholder: |
        **As a** blog visitor
        **I want** to search for blog posts by keyword
        **So that** I can quickly find relevant content
    validations:
      required: true

  - type: textarea
    id: business-value
    attributes:
      label: Business Value (Optional)
      description: Why is this user story important?
      placeholder: "Improves user experience by making content discoverable"
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria-functional
    attributes:
      label: Acceptance Criteria - Functional Requirements
      description: Specific, testable requirements using Given/When/Then format
      placeholder: |
        - [ ] **Given** I am on the blog homepage, **When** I enter a search term, **Then** I see relevant blog posts
        - [ ] **Given** I search for a keyword, **When** results are displayed, **Then** they are ranked by relevance
        - [ ] **Given** no results are found, **When** I search, **Then** I see a helpful "no results" message
    validations:
      required: false

  - type: checkboxes
    id: gdpr-considerations
    attributes:
      label: GDPR Considerations
      description: Does this involve personal data?
      options:
        - label: Involves personal data processing
        - label: GDPR compliance review needed
        - label: Not applicable

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies (Optional)
      description: What other user stories or requirements must be completed first?
      placeholder: |
        - US-XXXXX: Other user story that must be done first
        - Infrastructure or technical requirements
    validations:
      required: false

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes (Optional)
      description: Implementation hints or technical considerations
      placeholder: |
        - Consider search result caching for performance
        - Ensure search queries are properly escaped
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Next Steps

        1. Story will be reviewed and refined during backlog grooming
        2. BDD scenarios will be created in technical documentation
        3. Story will be added to the Requirements Traceability Matrix
        4. Implementation will follow the [BDD + RTM Development Workflow](../CLAUDE.md#bdd--rtm-development-workflow)

        **Traceability** - This story will be automatically linked to the parent epic and tracked in the RTM.