# GDPR Data Retention Policies
# Complies with French CNIL guidelines and GDPR Article 5(1)(e)

retention_policies:
  # Blog Comments
  comments:
    retention_period_days: 1095  # 3 years
    fields:
      - content
      - author_name
      - email  # Only if consent given
      - ip_address  # Anonymized after 30 days
      - created_at
      - updated_at

    deletion_triggers:
      - user_request  # Right to be forgotten (GDPR Article 17)
      - retention_period_expired
      - consent_withdrawn

    anonymization:
      ip_addresses:
        after_days: 30
        method: "hash_with_salt"  # Keep for abuse detection

      email_addresses:
        on_consent_withdrawal: "immediate"
        method: "hash_irreversible"

  # System Logs
  system_logs:
    retention_period_days: 90
    fields:
      - timestamp
      - log_level
      - message
      - anonymized_ip  # Never store full IPs

    deletion_triggers:
      - retention_period_expired
      - storage_limit_reached

  # Application Metrics
  metrics:
    retention_period_days: 365
    fields:
      - timestamp
      - page_views  # Aggregated only
      - response_times
      - error_counts

    # No personal data in metrics
    anonymization: "aggregated_only"

  # Error Reports
  error_reports:
    retention_period_days: 180
    fields:
      - timestamp
      - error_message
      - stack_trace
      - anonymized_context

    # Ensure no personal data in error reports
    sanitization:
      - remove_email_patterns
      - remove_ip_patterns
      - remove_session_ids

# Consent Management
consent_types:
  functional:
    required: true
    description: "Essential for website functionality"
    purpose: "Comment submission and display"
    legal_basis: "legitimate_interest"

  analytics:
    required: false
    description: "Help us improve the website"
    purpose: "Usage analytics and performance monitoring"
    legal_basis: "consent"

  marketing:
    required: false
    description: "Optional email notifications about new posts"
    purpose: "Newsletter and content updates"
    legal_basis: "consent"

# Data Subject Rights (GDPR Chapter 3)
data_subject_rights:
  access:  # Article 15
    response_time_days: 30
    format: "json"
    include_data_sources: true

  rectification:  # Article 16
    response_time_days: 30
    automatic_propagation: true

  erasure:  # Article 17 (Right to be forgotten)
    response_time_days: 30
    conditions:
      - consent_withdrawn
      - personal_data_no_longer_necessary
      - unlawful_processing
      - user_request

  portability:  # Article 20
    response_time_days: 30
    format: "json"
    structured_format: true

# Automated Processing
automated_processing:
  comment_moderation:
    exists: true
    logic: "Keyword filtering and spam detection"
    human_review: true
    user_notification: true

  ip_geolocation:
    exists: false  # Disabled for privacy

  behavioral_analysis:
    exists: false  # Disabled for GDPR compliance