name: staging
debug: false
host: "0.0.0.0"
port: 8000
reload: false

database:
  url: "${DATABASE_URL}"
  echo: false
  pool_size: 10
  max_overflow: 20

security:
  secret_key: "${SECRET_KEY}"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  cors_origins:
    - "https://staging.yourdomain.com"

gdpr:
  data_retention_days: 1095  # 3 years
  anonymize_ips_after_days: 30
  require_consent: true
  test_mode: false

logging:
  level: "INFO"
  file: "quality/monitoring/logs/staging.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"

content:
  posts_per_page: 10
  cache_timeout: 3600  # 1 hour

email:
  enabled: true
  smtp_host: "${SMTP_HOST}"
  smtp_port: 587
  smtp_user: "${SMTP_USER}"
  smtp_password: "${SMTP_PASSWORD}"
  admin_email: "${ADMIN_EMAIL}"

monitoring:
  health_check_interval: 30
  metrics_enabled: true